describe('My First Test', () => {
    beforeEach(()=>{
        cy.visit('/login')
    })
    it('primer test',()=>{
        cy.contains('sesión')
        cy.get('input[name="correo"]').should('be.visible')
        cy.get('input[name="correo"]').type('plazadiego591@gmail.com')
        cy.get('input[name="password"]').type('Dinop841')
        cy.contains('niciar sesión con correo').click()
        cy.url().should('include','/home')
    })
    it('segundo test',()=>{
        cy.contains('sesión')
        cy.get('input[name="correo"]').should('be.visible')
        cy.get('input[name="correo"]').type('plazadiego591@gmail.com')
        cy.get('input[name="password"]').type('Dinop841')
        cy.contains('niciar sesión con correo').click()
        cy.url().should('include','/home')
        cy.contains('Programar viaje').click()
        cy.get('input[name="Destino"').type('las vizcachas')
        cy.contains('Buscar').click()
        cy.get('ion-select')
    })
  })