# Generated by Django 5.1.2 on 2024-10-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(default='S/A', max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('idviaje', models.AutoField(primary_key=True, serialize=False)),
                ('partida', models.CharField(max_length=50, null=True)),
                ('destino', models.CharField(default='S/D', max_length=50)),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
            ],
        ),
    ]
