# Generated by Django 5.1.2 on 2024-11-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
