# Generated by Django 5.1.2 on 2024-11-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_viaje_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='lugar_encuentro',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
