# Generated by Django 5.1.2 on 2024-11-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_viaje_lugar_encuentro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedesDuoc',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(default='S/N', max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
