# Generated by Django 5.1.2 on 2024-11-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_sedesduoc_delete_usuario_delete_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedesduoc',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
